apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-worldpoc
  name: hello-worldpoc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-worldpoc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-worldpoc
    spec:
      containers:
        - image: gcr.io/numeric-marker-290502/github.com/ponnarasiv/cloud-builder
          imagePullPolicy: IfNotPresent
          name: cloud-builder-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hello-worldpoc
  name: hello-worldpoc-hpa-eslb
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-worldpoc
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-worldpoc
  name: hello-worldpoc-service
  namespace: default
spec:
  clusterIP: 10.120.15.1
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32687
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: hello-worldpoc
  sessionAffinity: None
  type: LoadBalancer
